---
title: "HOVER data exploration"
output:
  html_document:
    body_placement: left
    code_folding: hide
    toc_float:                                                             
      collapse: true                                                      
      smooth_scroll: true 
header-includes:
  - \usepackage{titling}
  - \pretitle{\begin{flushleft}}
  - \posttitle{\end{flushleft}}
---

```{r setup, include=FALSE, warning=FALSE, echo=TRUE}
knitr::opts_chunk$set(echo = TRUE)

options(dplyr.summarise.inform = FALSE)

library(tableone)
```

<br> 

```{r, include=FALSE, warning=FALSE, echo=TRUE}
summary(hhdata2)
```

```{r, include=FALSE, warning=FALSE, echo=TRUE}
summary(inddata1)
```

Table 1: Characteristics of study cohort

```{r, include=FALSE, warning=FALSE, echo=TRUE}
hhIDs <- inddata1 %>%
  group_by(hrhhid) %>% summarize(hhsize=n())

counts <- hhdata1 %>%
  group_by(h10_hbv_rdt) %>% summarize(count=n())

hhdata2 <- merge(hhdata1, hhIDs, by = c("hrhhid"), all.x = T)
hhdata2 <- merge(hhdata2, counts, by = c("h10_hbv_rdt"), all.x = T)

table(hhdata2$h1_roof)
# list of variables
tab1varcleaned <- c("hhsize", "maternity")

numericvars <- c("hhsize") # age, under 5s in hh, total hh members

catvars <- c("h10_hbv_rdt_f", "maternity")

hovertab1 <- CreateTableOne(vars = tab1varcleaned, factorVars = catvars, data=hhdata2, strata = "h10_hbv_rdt_f", addOverall = T, test = F)

print(hovertab1, showAllLevels = TRUE )

# individual
countsind <- inddata1 %>%
  group_by(h10_hbv_rdt) %>% summarize(count=n())

inddata2 <- merge(inddata1, countsind, by = c("h10_hbv_rdt"), all.x = T)

indtab1varcleaned <- c("count")

indnumericvars <- c("count") # age, under 5s in hh, total hh members

indcatvars <- c("h10_hbv_rdt_f", "count",  "hhsize")

indhovertab1 <- CreateTableOne(vars = tab1varcleaned, factorVars = catvars, data=hhdata2, strata = "h10_hbv_rdt_f", addOverall = T, test = F, nonnormal = nonNormalVars, minMax = TRUE)



```



